### PR TITLE
Expand "Make" variables inside of values in the env dictionary on test rules

### LINKED ISSUE #3056: Bug: "Make" variable expansion in the `env` of test bundles does not work.
### Description

"Make" variable expansion support was added to rules_apple in [this commit](https://github.com/bazelbuild/rules_apple/commit/3c4111a2b2defdba8086a245d60af565273f2738) and shipped with version 3.6.0. This allows for Starlark like this to work without requiring a `--test_env` in a bazelrc.

```starlark
string_flag(
    name = "my_make_var",
    build_setting_default = "",
    make_variable = "MY_MAKE_VAR",
)

objc_library(
    name = "make_var_unit_test_lib",
    srcs = ["make_var_unit_test.m"],
)

ios_unit_test(
    name = "MakeVarUnitTest",
    deps = [":make_var_unit_test_lib"],
    env = {
        "MY_MAKE_VAR": "$(MY_MAKE_VAR)",
    },
    toolchains = [":my_make_var"],
)
```

This works well enough when building with Bazel's CLI. With Xcode, however, the scheme that is generated for this test produces the uninterpolated value for the `env`. Is this possible to support in the xcodeproj generator? 

### Reproduction steps

1. Create a `string_flag` with a `make_variable` value
2. Create a `*_unit_test` that takes the `string_flag` as one of its `toolchains` and expands the value in its `env` attr.
3. Create an `xcodeproj` that takes the unit test as a top-level target.
4. Generate the xcodeproj.

### Expected behavior

Observe that the generated scheme has the literal `$(MY_MAKE_VAR)` (or whatever your `make_variable` was named), and not the interpolated value from bazelrc or even the default value. 

### rules_xcodeproj version

2.5.1

### Xcode version

15F31d

### Bazel version

7.2.1

### rules_apple version

3.6.0

### rules_swift version

2.0.0

### Additional information

I am using incremental generation and automatic scheme generation.

### PR DESCRIPTION
**Pull request by aaronsky**
Fixes #3056

This PR implements a gap introduced when bazelbuild/rules_apple#2476 was introduced, where expandable env settings on test rules would not be expanded into the xcscheme during generation. There are a couple of things that reviewers should be aware of before proceeding with this change:

- This change is not considerate of the rules_apple being used, meaning that it assumes the developer is using at least version [3.6.0](https://github.com/bazelbuild/rules_apple/releases/tag/3.6.0) (when the breaking changes in #2476 were introduced). This is not good and should be considered a blocker, but I don't know how to address this with the tools offered by the ruleset or Bazel.
- This change as-implemented requires regeneration of the xcschemes if the configured value of the "Make" variable ever changes.

### CODE REVIEW

**Comment by brentleyjones** [comment]
> This change is not considerate of the rules_apple being used, meaning that it assumes the developer is using at least version [3.6.0](https://github.com/bazelbuild/rules_apple/releases/tag/3.6.0) (when the breaking changes in [Fix label encoding in incremental generators #2476](https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2476) were introduced). This is not good and should be considered a blocker, but I don't know how to address this with the tools offered by the ruleset or Bazel.

I'm fine with bumping our minimum required version of **rules_apple** to 3.6.0. I agree there is no good way to detect this otherwise. Though, we could add a flag to go back to the old behavior? I would rather just bump our dep though.

> This change as-implemented requires regeneration of the xcschemes if the configured value of the "Make" variable ever changes.

I don't think there is a better way?

**Comment by aaronsky** [comment]
I've increasingly come to regret the way I introduced support for this feature in rules_apple. I think the most flexible behavior from a UX standpoint is a way to map Bazel settings to project-level xcconfigs, so they're available to the scheme without having to regenerate them, but then you'd need to regenerate the xcconfig instead.

I can put up a new commit that bumps the minimum rules_apple to 3.6.0.

**Comment by congt** [comment]
Any progress on this? We encounter exactly the same problem.

**Review by brentleyjones — APPROVED** [review]

**Comment by aaronsky** [comment]
@brentleyjones anything else we need to do to get this landed?

**Review by luispadron — APPROVED** [review]

**Comment by luispadron** [comment]
@congt would y'all be able to test this change in Square and see if it fixes the issue

**Comment by congt** [comment]
> @congt would y'all be able to test this change in Square and see if it fixes the issue

Just verified it works for us

**Comment by brentleyjones** [comment]
Thanks everyone!

**Pull request merged**
