### PR TITLE
Update rules_ios to latest and enable bzlmod

### PR DESCRIPTION
**Pull request by luispadron**
Updates to use rules_ios 3.1.0 and enables bzlmod. 

rules_ios is lacking support for Bazel > 6.x: https://github.com/bazel-ios/rules_ios/issues/795

### CODE REVIEW

**Comment by luispadron** [comment]
Current blocker: 

```sh
Generating "rules_ios.xcodeproj"
ERROR: /Users/lpadron/Development/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj~override~internal~rules_xcodeproj_generated/generator/xcodeproj/BUILD:12:10: error loading package 'iOSApp': Unable to find package for @[unknown repo 'build_bazel_rules_apple' requested from @]//apple:versioning.bzl: The repository '@[unknown repo 'build_bazel_rules_apple' requested from @]' could not be resolved: No repository visible as '@build_bazel_rules_apple' from main repository. and referenced by '@rules_xcodeproj~override~internal~rules_xcodeproj_generated//generator/xcodeproj:xcodeproj'
ERROR: Analysis of target '@rules_xcodeproj~override~internal~rules_xcodeproj_generated//generator/xcodeproj:xcodeproj' failed; build aborted: Analysis failed
```

**Comment by brentleyjones** [comment]
I can look at this Monday.

**Comment by brentleyjones** [comment]
Per offline, this is good to go in as is (when others approve it).

**Review by thiagohmcruz — APPROVED** [review]

**Comment by luispadron** [comment]
So it now has two rules_ios CI jobs, both using rules_ios 3.1.0:

- One with bzlmod enabled using Bazel 6.4.0
- One without bzlmod enabled using Bazel 6.4.0

**Review by mattrobmattrob — APPROVED** [review]

**Pull request merged**
