### PR TITLE
Change all references of "SwiftUI Previews" to "Xcode Previews"

### PR DESCRIPTION
**Pull request by adincebic**
Related to https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2554

### CODE REVIEW

**Comment by brentleyjones** [comment]
Thanks! I edited the PR to say it was related, since it doesn't quite close it out.

**Review by brentleyjones — APPROVED** [review]

**Review by mattrobmattrob — APPROVED** [review]

**Comment by adincebic** [comment]
> Thanks! I edited the PR to say it was related, since it doesn't quite close it out.

Curious to know what did I miss? I did a grep and it seems that there are no more references to SwiftUI Previews.

**Comment by brentleyjones** [comment]
There is also the bazel configs. But those would require a migration, so I don't want you to address them as part of this PR.

**Comment by brentleyjones** [comment]
To get CI to pass you need to update the fixtures as well.

**Comment by adincebic** [comment]
> To get CI to pass you need to update the fixtures as well.

Gonna deal with that tomorrow.

**Review by brentleyjones — APPROVED** [review]

**Review by brentleyjones — APPROVED** [review]

**Review by brentleyjones — APPROVED** [review]

**Pull request merged**
