### PR TITLE
Remove `DEPLOYMENT_LOCATION` hack for BwB mode

### PR DESCRIPTION
**Pull request by brentleyjones**
Introduced in 2fee67adb287f3ea40b815cf2f078276e5e9a479, this is non longer needed after e600086cde98ff0f0736d41a3a3c26833fdd6b25 and possibly as early as after c17968b8425f62af5cdbe5cfe46c5b96d7ad5a3d.

### CODE REVIEW

**Review by luispadron — APPROVED** [review]
Tested working on our project.

**Comment by erikkerber** [comment]
Launched to device on Slack

**Review by erikkerber — APPROVED** [review]

**Comment by brentleyjones** [comment]
For extra safety, can y'all check that the `DYLD_LIBRARY_PATH` env variable is of a sane length?

**Comment by erikkerber** [comment]
Is this what you're looking for?

CleanShot 2023-12-15 at 11 19 31@2x

**Comment by erikkerber** [comment]
I guess on sim it's a little spicier

CleanShot 2023-12-15 at 11 21 34@2x

**Comment by brentleyjones** [comment]
The sim one. Looks like it gets cut off, but doesn't seem to include much more, right?

**Comment by erikkerber** [comment]
Fixed

CleanShot 2023-12-15 at 11 27 41@2x

**Pull request merged**
